### ISSUE TITLE
Rename Bitcoin Merchant's Toolbox to BTC Toolbox

### ISSUE THREAD

**Issue by EAWF** [EAWF/BTC-Toolbox#67]
YOUR FEEDBACK REQUESTED:

I've been considering renaming this Repo to BTC Toolbox so as to match up with the domain name?

What say you?

@Septem151 @coinables @PeterNSteinmetz ?

**Comment by coinables** [comment]
SEO would be much better if you shorten it to match the domain.

**Comment by EAWF** [comment]
I agree.

**Comment by EAWF** [comment]
OK, made name change.
